# Generated by Django 2.1.5 on 2019-10-30 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrollingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crolling_now', models.BooleanField(default=False)),
                ('crolling_start', models.DateTimeField(auto_now=True)),
                ('crolling_num', models.IntegerField(default=1)),
                ('crolling_sum', models.IntegerField(default=1)),
                ('now_code', models.TextField(default='none', max_length=20)),
                ('now_num', models.IntegerField(default=1)),
                ('now_sum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
